### ISSUE TITLE
lock button gap

### ISSUE THREAD

**Issue by jonyrock** [chartwerk/grafana-chartwerk-panel#36]
![image](https://user-images.githubusercontent.com/1022757/83946735-f5817080-a812-11ea-9fd5-e37f1c43ba4a.png)

maybe we can move the lock button closer to the range?

**Comment by corpglory-dev** [comment]
fixed in https://github.com/chartwerk/grafana-chartwerk-panel/commit/afcbac67e0bb03d0c4418e551e8810f70455df53
